name: Building Exilence BR for all Platforms
on:
  push:
    tags:
      - 'v*'
jobs:
  upload-release:
    runs-on: ubuntu-latest
    needs: [build-win, build-linux]
    steps:
      - uses: actions/checkout@v1
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Exilence-BR*.exe
            Exilence-BR*.exe.blockmap
            Exilence-BR*.AppImage
            Exilence-BR*.AppImage.blockmap
            latest*.yml
  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.20.2
          cache: 'npm'
      - run: npm ci
      - run: npm run smoke-build-win
      - uses: actions/upload-artifact@v4
        with:
          name: exilence-br-win
          path: |
            dist/Exilence-BR*.exe
            dist/Exilence-BR*.exe.blockmap
            dist/latest*.yml
  # build-mac:
  #   runs-on: macos-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - uses: actions/setup-node@v3
  #     with:
  #       node-version: 16.20.2
  #       cache: 'npm'
  #   - run: npm ci
  #   - run: npm run smoke-build-mac
  #   - run: ls dist/
  #   - uses: actions/upload-artifact@v4
  #     with:
  #       name: exilence-br-mac
  #       path: dist/Exilence-BR*.dmg
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.20.2
          cache: 'npm'
      - run: npm ci
      - run: npm run smoke-build-linux
      - uses: actions/upload-artifact@v4
        with:
          name: exilence-br-linux
          path: |
            dist/Exilence-BR*.AppImage
            dist/Exilence-BR*.AppImage.blockmap
            dist/latest*.yml
